allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@perspective-dev/client@5.3.0'
  - '@perspective-dev/react@5.3.0'
  - '@perspective-dev/server@5.3.0'
  - '@perspective-dev/viewer-charts@5.3.0'
  - '@perspective-dev/viewer-datagrid@5.3.0'
  - '@perspective-dev/viewer@5.3.0'

onlyBuiltDependencies:
  - esbuild

overrides:
  react: 19.2.6
  react-dom: 19.2.6
