# @package _global_
defaults:
  - /gateway: omnibus
  - _self_

# csp-gateway-start --config-dir=csp_gateway/server/demo +config=omnibus_legacy
#
# Same as the `omnibus` config, but serves the legacy Perspective/React UI instead of the
# default spaday-based UI. Requires the bundled Javascript build.

port: 8000

gateway:
  settings:
    UI_PROVIDER: default
