from typing import TYPE_CHECKING, Any

from pydantic import Field

from csp_gateway.server import ChannelSelection, GatewayChannels, GatewayModule

# Imported from the leaf module, not the `csp_gateway.server` package: that package re-exports
# `.modules` before `.web`, so it is only partially initialized while this module is imported.
from csp_gateway.server.web import GatewayWebApp

if TYPE_CHECKING:
    from csp_gateway.server.web.spaday_ui import GatewayUI


class MountSendForm(GatewayModule):
    """Spaday UI: a "send data to a channel" panel that generates an input form per sendable channel.

    This is a **presentation** module for the spaday UI provider only — its `ui()` hook is a no-op under
    the default (React) UI, and it mounts no routes and touches no data (it relies on the send REST
    endpoints that `MountRestRoutes` provides). It is deliberately separate from `MountRestRoutes` so that
    form/appearance configuration never conflates with REST routing, which is independent of the UI.

    A form is generated for each channel that has a send adapter (registered via `add_send_channel`)
    and is included in `mount_send`; dict-basket channels get a key selector (the POST targets
    `/send/{channel}/{key}`). Controls and native validation are generated by spaday's `form()` from
    each channel struct's JSON schema; `form_overrides` relabels or drops individual fields without
    touching the data or routing layers.
    """

    mount_send: ChannelSelection = Field(
        default_factory=ChannelSelection,
        description=(
            "Send channels to render a form for. Should match the send channels `MountRestRoutes` actually "
            "mounts (its `mount_send` / `force_mount_all`), so the UI never shows a form that POSTs to a "
            "route that was intentionally not mounted. Defaults to all sendable channels."
        ),
    )

    form_overrides: dict[str, dict[str, Any]] = Field(
        default_factory=dict,
        description=(
            "Per-field overrides for the generated send form, keyed by 'channel.field' (specific channel) "
            "or 'field' (any channel). Each value is a mapping with 'label' (relabel) and/or 'exclude' "
            "(drop the field); the control itself is chosen by spaday's form() from the channel struct's "
            "JSON schema. Presentation-only and transport-agnostic."
        ),
    )

    def connect(self, channels: GatewayChannels) -> None:
        # NO-OP: this module contributes UI only.
        ...

    def rest(self, app: GatewayWebApp) -> None:
        # NO-OP: no REST routes; the form posts to the send routes mounted by MountRestRoutes.
        ...

    def ui(self, app: "GatewayUI") -> None:
        # Build a "send data to a channel" panel from the genuinely sendable channels (those with a
        # send adapter registered via `add_send_channel`). Dict baskets get a key selector.
        from csp_gateway.server.web.spaday_ui import Region, SendSpec

        web_app = app.web_app
        channels = web_app.gateway.channels
        # Only channels whose send route is mounted (per `mount_send`) — otherwise the form would POST
        # to a `/send/{channel}` route that `MountRestRoutes` intentionally did not mount.
        allowed = set(self.mount_send.select_from(web_app.gateway.channels_model))

        forms = []
        for descriptor in channels.send_channel_descriptors():
            channel = descriptor.channel
            if channel not in allowed:
                continue
            forms.append(
                SendSpec(
                    channel=channel,
                    url=web_app.api_path(f"/send/{channel}", self.api_version),
                    model=descriptor.model,
                    keys=descriptor.keys,
                    overrides=self._overrides_for(channel),
                )
            )

        if forms:
            app.add(Region.DRAWER_BOTTOM, app.send_panel(forms), label="Send data to channel")
            seeds: dict[str, Any] = {"send_channel": forms[0].channel}
            for spec in forms:
                if spec.keys:
                    seeds[f"send_key_{spec.channel}"] = spec.keys[0]
            app.seed_store(**seeds)

    def _overrides_for(self, channel: str) -> dict[str, Any]:
        """Resolve `form_overrides` for one channel: 'channel.field' entries win over bare 'field' ones."""
        resolved: dict[str, Any] = {}
        for key, cfg in self.form_overrides.items():
            if "." not in key:
                resolved[key] = cfg
        for key, cfg in self.form_overrides.items():
            if "." in key:
                ch, field_name = key.split(".", 1)
                if ch == channel:
                    resolved[field_name] = cfg
        return resolved
